"""category and extension migrate

Revision ID: 72de50d98fc5
Revises: 7ac63ef85009
Create Date: 2026-08-05 20:00:48.972523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72de50d98fc5'
down_revision: Union[str, Sequence[str], None] = '7ac63ef85009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('extension',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_extension_id'), 'extension', ['id'], unique=False)
    op.add_column('file', sa.Column('extension_id', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_file_id'), 'file', ['id'], unique=False)
    op.create_foreign_key(None, 'file', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'file', 'extension', ['extension_id'], ['id'])
    op.drop_column('file', 'category')
    op.drop_column('file', 'extension')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('extension', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('category', sa.VARCHAR(), server_default=sa.text("'other'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_index(op.f('ix_file_id'), table_name='file')
    op.drop_column('file', 'category_id')
    op.drop_column('file', 'extension_id')
    op.drop_index(op.f('ix_extension_id'), table_name='extension')
    op.drop_table('extension')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
