"""file version migrate

Revision ID: 7ac63ef85009
Revises: b7c30ff0456a
Create Date: 2026-08-05 16:22:13.810062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac63ef85009'
down_revision: Union[str, Sequence[str], None] = 'b7c30ff0456a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'uploader_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploader_name', sa.VARCHAR(), server_default=sa.text("'anonimous'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
