"""table for mime type

Revision ID: 9ae4f8d9c20f
Revises: 38f71cf32795
Create Date: 2026-08-05 22:52:08.704885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae4f8d9c20f'
down_revision: Union[str, Sequence[str], None] = '38f71cf32795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mime_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mime_type_id'), 'mime_type', ['id'], unique=False)
    op.add_column('file', sa.Column('mime_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'file', 'mime_type', ['mime_type_id'], ['id'])
    op.drop_column('file', 'mime_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'mime_type_id')
    op.drop_index(op.f('ix_mime_type_id'), table_name='mime_type')
    op.drop_table('mime_type')
    # ### end Alembic commands ###
