"""file table update migrate

Revision ID: b7c30ff0456a
Revises: fa58d0f3a257
Create Date: 2026-08-05 10:13:41.253117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7c30ff0456a'
down_revision: Union[str, Sequence[str], None] = 'fa58d0f3a257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('extension', sa.String(), nullable=True))
    op.add_column('file', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('file', sa.Column('category', sa.String(), server_default='other', nullable=False))
    op.add_column('file', sa.Column('uploader_name', sa.String(), server_default='anonimous', nullable=False))
    op.add_column('file', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('file', sa.Column('upload_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'upload_at')
    op.drop_column('file', 'password_hash')
    op.drop_column('file', 'uploader_name')
    op.drop_column('file', 'category')
    op.drop_column('file', 'mime_type')
    op.drop_column('file', 'extension')
    # ### end Alembic commands ###
