"""fix: cascade deleting.

Revision ID: c18939f92eb2
Revises: ef9151f53b98
Create Date: 2026-08-08 18:13:31.117878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c18939f92eb2'
down_revision: Union[str, Sequence[str], None] = 'ef9151f53b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('extension_mime_type_id_fkey'), 'extension', type_='foreignkey')
    op.create_foreign_key(None, 'extension', 'mime_type', ['mime_type_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('file_extension_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'extension', ['extension_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('mime_type_category_id_fkey'), 'mime_type', type_='foreignkey')
    op.create_foreign_key(None, 'mime_type', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mime_type', type_='foreignkey')
    op.create_foreign_key(op.f('mime_type_category_id_fkey'), 'mime_type', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_extension_id_fkey'), 'file', 'extension', ['extension_id'], ['id'])
    op.drop_constraint(None, 'extension', type_='foreignkey')
    op.create_foreign_key(op.f('extension_mime_type_id_fkey'), 'extension', 'mime_type', ['mime_type_id'], ['id'])
    # ### end Alembic commands ###
