"""Extension to mime type foreign key added.

Revision ID: ef9151f53b98
Revises: 1a14acfc8a16
Create Date: 2026-08-07 18:40:09.034849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9151f53b98'
down_revision: Union[str, Sequence[str], None] = '1a14acfc8a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extension', sa.Column('mime_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'extension', 'mime_type', ['mime_type_id'], ['id'])
    op.drop_constraint(op.f('file_mime_type_id_fkey'), 'file', type_='foreignkey')
    op.drop_column('file', 'mime_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('mime_type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('file_mime_type_id_fkey'), 'file', 'mime_type', ['mime_type_id'], ['id'])
    op.drop_constraint(None, 'extension', type_='foreignkey')
    op.drop_column('extension', 'mime_type_id')
    # ### end Alembic commands ###
